[versions]
agp = "8.13.2"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
fragment = "1.8.9"
viewpager = "1.1.0"
annotation = "1.9.1"
preferencemanager = "1.2.1"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }
viewpager = { group = "androidx.viewpager", name = "viewpager", version.ref = "viewpager"}
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation"}
preferencemanager = { group = "androidx.preference", name = "preference", version.ref = "preferencemanager"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

